language: objective-c
osx_image: xcode11.2

xcode_workspace: NinchatSDK.xcworkspace
xcode_scheme: NinchatSDK
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 8

before_install:
  - git submodule update --init --recursive
  - brew update

  # update Go-Pods to the latest version
  - brew install go
  - brew upgrade go

  - go get -u golang.org/x/mobile/cmd/gomobile
  - export PATH=$PATH:~/go/bin
  - gomobile init
  - ./update-go-framework.sh
  
  - brew install cocoapods
  - brew upgrade cocoapods
  - pod setup

script:
  - pod update
  - pod install
  - set -o pipefail && xcodebuild -workspace NinchatSDK.xcworkspace -scheme NinchatSDK -configuration "Release" | xcpretty -t; test ${PIPESTATUS[0]} -eq 0