language: objective-c
osx_image: xcode11.2

xcode_workspace: NinchatSDK.xcworkspace
xcode_scheme: NinchatSDK
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 8

cache: cocoapods

before_install:
  - git submodule update --init --recursive

  - brew install go
  - go get -u golang.org/x/mobile/cmd/gomobile
  - export PATH=$PATH:~/go/bin
  - gomobile init
  - ./update-go-framework.sh

  # install cocoapods manually
  # related to: https://stackoverflow.com/questions/58958185/travis-ci-gets-stuck-at-cocoapods-installation
  - mkdir ~/.cocoapods/repos && cd ~/.cocoapods/repos
  - git clone "https://github.com/CocoaPods/Specs" master --depth 1
  - cd master
  - git fetch --unshallow
  - pod setup

script:
  - set -o pipefail && xcodebuild -workspace NinchatSDK.xcworkspace -scheme NinchatSDK -configuration "Release"