language: objective-c
osx_image: xcode11.2

xcode_workspace: NinchatSDK.xcworkspace
xcode_scheme: NinchatSDK
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 8

cache: cocoapods

before_install:
  - git submodule update --init --recursive

  - brew install go
  - brew install cocoapods

  # update Go-Pods to the latest version
  - brew update
  - brew upgrade go
  - brew upgrade cocoapods

  - go get -u golang.org/x/mobile/cmd/gomobile
  - export PATH=$PATH:~/go/bin
  - gomobile init
  - ./update-go-framework.sh
  
  - travis_wait 45 pod setup

script:
  - set -o pipefail && xcodebuild -workspace NinchatSDK.xcworkspace -scheme NinchatSDK -configuration "Release"