language: objective-c
osx_image: xcode11.2

xcode_workspace: NinchatSDK.xcworkspace
xcode_scheme: NinchatSDK
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 8

before_install:
  - brew install go
  - go get -u golang.org/x/mobile/cmd/gomobile
  - export PATH=$PATH:~/go/bin
  - gomobile init
  - git submodule update --init --recursive
  - gem install cocoapods -v '0.32.1'
  
install:
  - gem install xcpretty 
  - pod setup

script:
  - ./update-go-framework.sh
  - xcodebuild clean
  - xcodebuild -workspace NinchatSDK.xcworkspace -scheme NinchatSDK -configuration "Release" | xcpretty -c