language: objective-c
osx_image: xcode11.2

xcode_workspace: NinchatSDK.xcworkspace
xcode_scheme: NinchatSDK
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 8

before_install:
  - git submodule update --init --recursive

  - brew install go
  - go get -u golang.org/x/mobile/cmd/gomobile
  - export PATH=$PATH:~/go/bin
  - gomobile init
  - ./update-go-framework.sh

  - gem install cocoapods -v '0.32.1'
  - pod setup
  - pod install

script:
  - xcodebuild -workspace NinchatSDK.xcworkspace -scheme NinchatSDK -configuration "Release"