
// Objective-C API for talking to the following Go packages
//
//	github.com/ninchat/ninchat-go/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Client_FRAMEWORK_H__
#define __Client_FRAMEWORK_H__

#include "ref.h"
#include "Client.objc.h"
#include "universe.objc.h"

#endif
